go:
  version: 1.25
repository:
  path: github.com/stakater/alert-az-do
build:
  binaries:
  - name: alert-az-do
    path: cmd/alert-az-do 
  flags: -a -tags netgo
crossbuild:
  platforms:
  - linux/amd64
